name: rush
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.4
  firebase_storage: ^12.3.7
  get_it: ^8.0.3
  flutter_launcher_icons: ^0.14.2
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  provider: ^6.1.2
  intl: ^0.19.0
  image_picker: ^1.0.7
  timeago: ^3.6.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  badges: ^3.1.2
  equatable: ^2.0.5
  flutter_image_compress: ^2.2.0
  cached_network_image: ^3.3.1
  http: ^1.2.2
  cloudinary_flutter: ^1.3.0
  cloudinary_url_gen: ^1.6.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.1
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  firebase_messaging: ^15.1.6
  flutter_native_splash: ^2.4.3
  mockito: ^5.4.4
  build_runner: ^2.4.13
  firebase_auth_mocks: ^0.14.1
  firebase_database_mocks: ^0.7.1
  flutter_facebook_auth: ^6.2.0
  font_awesome_flutter: ^10.8.0
  google_sign_in: ^6.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/launcher_icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: BeVietnamPro
      fonts:
        - asset: assets/fonts/BeVietnamPro-Regular.ttf
        - asset: assets/fonts/BeVietnamPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/BeVietnamPro-Light.ttf
          weight: 300
        - asset: assets/fonts/BeVietnamPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/BeVietnamPro-SemiBold.ttf
          weight: 600
